// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    id,
    user_id,
    seat_id,
    booking_code,
    status
)
VALUES (
    $1,
    $2,
    $3, 
    $4,
    $5
)
RETURNING id, user_id, seat_id, booking_code, status, created_at
`

type CreateBookingParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	SeatID      pgtype.UUID `json:"seat_id"`
	BookingCode string      `json:"booking_code"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ID,
		arg.UserID,
		arg.SeatID,
		arg.BookingCode,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.BookingCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
