// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flights.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlight = `-- name: CreateFlight :one
INSERT INTO flights (
    id,
    flight_number, 
    departure_airport, 
    arrival_airport, 
    boarding_at,
    departure_at,
    arrival_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, flight_number, departure_airport, arrival_airport, boarding_at, departure_at, arrival_at, created_at, updated_at
`

type CreateFlightParams struct {
	ID               pgtype.UUID        `json:"id"`
	FlightNumber     string             `json:"flight_number"`
	DepartureAirport string             `json:"departure_airport"`
	ArrivalAirport   string             `json:"arrival_airport"`
	BoardingAt       pgtype.Timestamptz `json:"boarding_at"`
	DepartureAt      pgtype.Timestamptz `json:"departure_at"`
	ArrivalAt        pgtype.Timestamptz `json:"arrival_at"`
}

func (q *Queries) CreateFlight(ctx context.Context, arg CreateFlightParams) (Flight, error) {
	row := q.db.QueryRow(ctx, createFlight,
		arg.ID,
		arg.FlightNumber,
		arg.DepartureAirport,
		arg.ArrivalAirport,
		arg.BoardingAt,
		arg.DepartureAt,
		arg.ArrivalAt,
	)
	var i Flight
	err := row.Scan(
		&i.ID,
		&i.FlightNumber,
		&i.DepartureAirport,
		&i.ArrivalAirport,
		&i.BoardingAt,
		&i.DepartureAt,
		&i.ArrivalAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
