// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	SeatID      pgtype.UUID        `json:"seat_id"`
	BookingCode string             `json:"booking_code"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Flight struct {
	ID               pgtype.UUID        `json:"id"`
	FlightNumber     string             `json:"flight_number"`
	DepartureAirport string             `json:"departure_airport"`
	ArrivalAirport   string             `json:"arrival_airport"`
	BoardingAt       pgtype.Timestamptz `json:"boarding_at"`
	DepartureAt      pgtype.Timestamptz `json:"departure_at"`
	ArrivalAt        pgtype.Timestamptz `json:"arrival_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Seat struct {
	ID         pgtype.UUID        `json:"id"`
	FlightID   pgtype.UUID        `json:"flight_id"`
	SeatNumber string             `json:"seat_number"`
	SeatClass  string             `json:"seat_class"`
	Price      int64              `json:"price"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SeatHold struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	SeatID    pgtype.UUID        `json:"seat_id"`
	HoldToken pgtype.UUID        `json:"hold_token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	PhoneNumber string             `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
