// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFlight(ctx context.Context, arg CreateFlightParams) (Flight, error)
	CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error)
	CreateSeatHold(ctx context.Context, arg CreateSeatHoldParams) (SeatHold, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetActiveSeatHold(ctx context.Context, seatID pgtype.UUID) (SeatHold, error)
	GetConfirmedBooking(ctx context.Context, seatID pgtype.UUID) (Booking, error)
	LockSeat(ctx context.Context, id pgtype.UUID) (Seat, error)
}

var _ Querier = (*Queries)(nil)
