// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seat_hold.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveHold = `-- name: CountActiveHold :one
SELECT COUNT(*)
FROM seat_holds
WHERE seat_id = $1
AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) CountActiveHold(ctx context.Context, seatID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveHold, seatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSeatHold = `-- name: CreateSeatHold :one
INSERT INTO seat_holds (id, user_id, seat_id, hold_token, expires_at)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP + INTERVAL '10 minutes')
RETURNING id, user_id, seat_id, hold_token, created_at, expires_at
`

type CreateSeatHoldParams struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	SeatID    pgtype.UUID `json:"seat_id"`
	HoldToken pgtype.UUID `json:"hold_token"`
}

func (q *Queries) CreateSeatHold(ctx context.Context, arg CreateSeatHoldParams) (SeatHold, error) {
	row := q.db.QueryRow(ctx, createSeatHold,
		arg.ID,
		arg.UserID,
		arg.SeatID,
		arg.HoldToken,
	)
	var i SeatHold
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.HoldToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getActiveSeatHold = `-- name: GetActiveSeatHold :one
SELECT id, user_id, seat_id, hold_token, created_at, expires_at
FROM seat_holds
WHERE seat_id = $1
AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetActiveSeatHold(ctx context.Context, seatID pgtype.UUID) (SeatHold, error) {
	row := q.db.QueryRow(ctx, getActiveSeatHold, seatID)
	var i SeatHold
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.HoldToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getConfirmedBooking = `-- name: GetConfirmedBooking :one
SELECT id, user_id, seat_id, booking_code, status, created_at
FROM bookings
WHERE seat_id = $1
AND status = 'CONFIRMED'
`

func (q *Queries) GetConfirmedBooking(ctx context.Context, seatID pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getConfirmedBooking, seatID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.BookingCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const lockSeat = `-- name: LockSeat :one
SELECT id, flight_id, seat_number, seat_class, price, created_at 
FROM seats
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockSeat(ctx context.Context, id pgtype.UUID) (Seat, error) {
	row := q.db.QueryRow(ctx, lockSeat, id)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.SeatNumber,
		&i.SeatClass,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
