// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSeat = `-- name: CreateSeat :one
INSERT INTO seats (
    id,
    flight_id,
    seat_number,
    seat_class,
    price
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, flight_id, seat_number, seat_class, price, created_at
`

type CreateSeatParams struct {
	ID         pgtype.UUID `json:"id"`
	FlightID   pgtype.UUID `json:"flight_id"`
	SeatNumber string      `json:"seat_number"`
	SeatClass  string      `json:"seat_class"`
	Price      int64       `json:"price"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, createSeat,
		arg.ID,
		arg.FlightID,
		arg.SeatNumber,
		arg.SeatClass,
		arg.Price,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.SeatNumber,
		&i.SeatClass,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
