// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(
    id,
    name,
    email,
    phone_number
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, email, phone_number, created_at
`

type CreateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Email       string      `json:"email"`
	PhoneNumber string      `json:"phone_number"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}
